#Write a function nearly_equal to test whether two strings are nearly equal. Two strings a and b are nearly equal when a can be generated by a single mutation on b.
#Create a class Flower(name). Add the attribute petal Color at runtime. If the flower has the attribute petal Color then display '<petal Color> <name>' else display 'Unknown Flower'.
#Compare two lists entered by user?
# Print Armstrong numbers in the range (100,500)?
import math as m
print("Armstrong numbers between 100 & 500 are : ")
sum=0
for i in range(100,500):
    for j in str(i):
        sum+=m.pow(int(j),3)
    if i==sum:
        print(i,end=" ")
    sum=0



